# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Estilo
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

    # Seguridad
    avoid_print: true
    avoid_web_libraries_in_flutter: true

    # Calidad
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_brace_in_string_interps: true

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"         # Archivos generados
    - "**/*.freezed.dart"
