// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3xgeB8UYht877jl9WOo-ffK0GkIIKNW4',
    appId: '1:585400881584:web:8ced3f31f2001f6ff08675',
    messagingSenderId: '585400881584',
    projectId: 'custodiam',
    authDomain: 'custodiam.firebaseapp.com',
    storageBucket: 'custodiam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw2DfGsfG9trg7iPGNDe6LqaNHCJDnPR8',
    appId: '1:585400881584:android:bd74e81889f76fd2f08675',
    messagingSenderId: '585400881584',
    projectId: 'custodiam',
    storageBucket: 'custodiam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKlKK0Y6ev3drKZtHDQDKTdwQEJjHf6ag',
    appId: '1:585400881584:ios:2b53286439ecfb6cf08675',
    messagingSenderId: '585400881584',
    projectId: 'custodiam',
    storageBucket: 'custodiam.firebasestorage.app',
    iosBundleId: 'es.custodiam.app',
  );
}
